version: 0.2

env:
  variables:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - npm install
      - npm_config_user=root npm install -g serverless
      - pip install -r requirements.txt
  build:
    commands:
      - coverage run -m pytest test/conftest.py
      - coverage report --fail-under=60
      - serverless deploy --stage $STAGE --region $REGION