Resources:
  CostExplorer:
    Type: AWS::S3::Bucket
    Properties: 
      VersioningConfiguration: 
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Sub ${self:service}-${AWS::AccountId}-${self:custom.stage}